vd:
  features:
    disable-security: true
#    disable-data-source: true

spring:
  application:
    name: video-downloader
  profiles:
    active: dev

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: info
    com.brokencodes.vd: debug