vd:
  features:
    disable-security: false
    disable-data-source: false

spring:
  application:
    name: video-downloader
  profiles:
    active: dev

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: info
    com.brokencodes.vd: debug